### ISSUE TITLE
Inference on ScanNet v2 RuntimeError: CUDA error: invalid argument

### ISSUE THREAD

**Issue by hazelAutumn** [hustvl/HAIS#34]
Hi, thanks for your excellent work.
I tried to reproduce the result of the pretrained model on the validation set of ScanNet v2.0. I followed the instructions in your repo to process the data and installation, but I faced this issue:
![image](https://user-images.githubusercontent.com/72719725/202862383-2c319c53-6ef3-4f96-ac85-0e151b8e3929.png)

Does anyone have any suggestions about the root of this issue? Thank you so much.

My environment:
- CUDA 10.2.
- spconv 1.0
- pytorch 1.1.0
- python 3.7

**Comment by Greatest-Marx** [comment]
Hi ~ have you solved this issue ？I run the code 'CUDA_VISIBLE_DVICES=0 python test.py --config config/hais_run1_scannet.yaml ', then it said 'RuntimeError : CUDA error : invalid argument'

**Comment by hazelAutumn** [comment]
Hi. Sorry, I dont remember how I solved this issue because I stopped working on this project 6 months ago.
Hope that you can fix the issue soon

**Comment by Greatest-Marx** [comment]
> Hi. Sorry, I dont remember how I solved this issue because I stopped working on this project 6 months ago. Hope that you can fix the issue soon

Thank u for your reply! I just solved this problem a few days ago, this issue may caused by incompatible between CUDA version and torch version
